package front;

import java.awt.Color;
import java.util.Arrays;


/**
 *
 * @author poletto
 */
public class cadastroFrame extends javax.swing.JFrame {

    
    char[] correctPassword = { 's', 'e', 'n', 'h', 'a', 'd', 'i', 'f', 'i', 'c', 'i', 'l' };
    char[] incorrectPassword = null;
    
    /**
     * Creates new form testFrame
     */
    public cadastroFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        mailLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        mailField = new javax.swing.JTextField();
        birthLabel = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        neighborhoodField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        neighborhoodLabel = new javax.swing.JLabel();
        rgLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        lastnameField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        lastnameLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        birthField = new javax.swing.JFormattedTextField();
        phoneField = new javax.swing.JFormattedTextField();
        cpfField = new javax.swing.JFormattedTextField();
        stateComboBox = new javax.swing.JComboBox<>();
        addressField = new javax.swing.JTextField();
        rgField = new javax.swing.JFormattedTextField();
        cellphoneLabel = new javax.swing.JLabel();
        cellphoneField = new javax.swing.JFormattedTextField();
        cepLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        cepField = new javax.swing.JFormattedTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mailLabel.setText("E-mail");

        phoneLabel.setText("Telefone");

        mailField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mailField.setText("joaodasilva@email.com.br");
        mailField.setToolTipText("digite um e-mail válido");
        mailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailFieldFocusLost(evt);
            }
        });

        birthLabel.setText("Data de nascimento");

        cityField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cityField.setText("São Paulo");
        cityField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cityFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cityFieldFocusLost(evt);
            }
        });

        stateLabel.setText("Estado");

        neighborhoodField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        neighborhoodField.setText("Centro");
        neighborhoodField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                neighborhoodFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                neighborhoodFieldFocusLost(evt);
            }
        });

        cityLabel.setText("Cidade");

        neighborhoodLabel.setText("Bairro");

        rgLabel.setText("R.G.");

        addressLabel.setText("Endereço");

        cpfLabel.setText("CPF");

        confirmButton.setText("Confirmar Cadastro");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        lastnameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lastnameField.setText("Silva");
        lastnameField.setToolTipText("Digite seu último nome");
        lastnameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnameFieldFocusLost(evt);
            }
        });

        nameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameField.setText("João");
        nameField.setToolTipText("Digite seu primeiro nome");
        nameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFieldFocusLost(evt);
            }
        });

        lastnameLabel.setText("Sobrenome");

        nameLabel.setText("Nome");

        try {
            birthField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        birthField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        birthField.setText("01/01/2000");
        birthField.setToolTipText("Digite sua data de nascimento");
        birthField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                birthFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                birthFieldFocusLost(evt);
            }
        });

        try {
            phoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        phoneField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phoneField.setText("(00) 1234-5678");
        phoneField.setToolTipText("Digite um número de telefone com DDD");
        phoneField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFieldFocusLost(evt);
            }
        });

        try {
            cpfField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpfField.setText("111.222.333-00");
        cpfField.setToolTipText("Digite seu CPF");
        cpfField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpfFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cpfFieldFocusLost(evt);
            }
        });

        stateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Paraná", "Paraíba", "Pará", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "Sergipe", "São Paulo", "Tocantins" }));
        stateComboBox.setToolTipText("");
        stateComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        addressField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addressField.setText("Av. Paulista, 000");
        addressField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressFieldFocusLost(evt);
            }
        });

        try {
            rgField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        rgField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rgField.setText("00.111.999-0");
        rgField.setToolTipText("Digite somente os números anteriores ao Dígito um R.G. (Registro Geral) válido");
        rgField.setSelectionEnd(12);
        rgField.setSelectionStart(12);
        rgField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rgFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rgFieldFocusLost(evt);
            }
        });

        cellphoneLabel.setText("Celular");

        try {
            cellphoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cellphoneField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cellphoneField.setText("(00) 1234-5678");
        cellphoneField.setToolTipText("Digite um número de telefone com DDD");
        cellphoneField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cellphoneFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cellphoneFieldFocusLost(evt);
            }
        });

        cepLabel.setText("CEP");

        loginLabel.setText("Login");

        passwordLabel.setText("Senha");

        loginField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        loginField.setText("SilvaJoao");
        loginField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginFieldFocusLost(evt);
            }
        });

        try {
            cepField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cepField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cepField.setText("11111-000");
        cepField.setToolTipText("Digite seu CEP");
        cepField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cepFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cepFieldFocusLost(evt);
            }
        });

        passwordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordField.setText("senhadificil");
        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFieldFocusLost(evt);
            }
        });

        jLabel1.setText("Salário");

        jLabel2.setText("Comissão");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("jTextField1");

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("jTextField2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(confirmButton)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rgLabel)
                            .addComponent(cpfLabel)
                            .addComponent(phoneLabel)
                            .addComponent(birthLabel)
                            .addComponent(mailLabel)
                            .addComponent(stateLabel)
                            .addComponent(lastnameLabel)
                            .addComponent(nameLabel)
                            .addComponent(neighborhoodLabel))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(birthField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastnameField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mailField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(neighborhoodField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneField)
                            .addComponent(cpfField)
                            .addComponent(stateComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rgField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cityLabel)
                            .addComponent(addressLabel)
                            .addComponent(cepLabel)
                            .addComponent(cellphoneLabel)
                            .addComponent(loginLabel)
                            .addComponent(passwordLabel)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addressField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(cellphoneField, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(cityField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(loginField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cepField)
                    .addComponent(passwordField)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel)
                    .addComponent(loginLabel)
                    .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnameLabel)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rgLabel)
                    .addComponent(rgField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLabel)
                    .addComponent(cpfField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cellphoneLabel)
                        .addComponent(cellphoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(phoneLabel)
                        .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthLabel)
                    .addComponent(birthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailLabel)
                    .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cepLabel)
                    .addComponent(cepField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stateLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cityLabel)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(neighborhoodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel)
                    .addComponent(neighborhoodLabel))
                .addGap(51, 51, 51)
                .addComponent(confirmButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mailField.setForeground(Color.gray);
        cityField.setForeground(Color.gray);
        neighborhoodField.setForeground(Color.gray);
        lastnameField.setForeground(Color.gray);
        nameField.setForeground(Color.gray);
        birthField.setForeground(Color.gray);
        phoneField.setForeground(Color.gray);
        cpfField.setForeground(Color.gray);
        addressField.setForeground(Color.gray);
        rgField.setForeground(Color.gray);
        cellphoneField.setForeground(Color.gray);
        loginField.setForeground(Color.gray);
        cepField.setForeground(Color.gray);
        passwordField.setForeground(Color.gray);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void mailFieldFocusGained(java.awt.event.FocusEvent evt) {                                      
        if (mailField.getText().equals("joaodasilva@email.com.br")){
            mailField.setText("");
            mailField.setForeground(Color.black);
        }
    }                                     

    private void mailFieldFocusLost(java.awt.event.FocusEvent evt) {                                    
        if (mailField.getText().equals("")) {
            mailField.setText("joaodasilva@email.com.br");
            mailField.setForeground(Color.gray);
        }
        else{
            mailField.setForeground(Color.black);
        }
    }                                   

    private void cityFieldFocusGained(java.awt.event.FocusEvent evt) {                                      
        if (cityField.getText().equals("São Paulo")){
            cityField.setText("");
            cityField.setForeground(Color.black);
        }
    }                                     

    private void cityFieldFocusLost(java.awt.event.FocusEvent evt) {                                    
        if (cityField.getText().equals("")) {
            cityField.setText("São Paulo");
            cityField.setForeground(Color.gray);
        }
        else{
            cityField.setForeground(Color.black);
        }
    }                                   

    private void neighborhoodFieldFocusGained(java.awt.event.FocusEvent evt) {                                              
        if (neighborhoodField.getText().equals("Centro")){
            neighborhoodField.setText("");
            neighborhoodField.setForeground(Color.black);
        }
    }                                             

    private void neighborhoodFieldFocusLost(java.awt.event.FocusEvent evt) {                                            
        if (neighborhoodField.getText().equals("")) {
            neighborhoodField.setText("Centro");
            neighborhoodField.setForeground(Color.gray);
        }
        else{
            neighborhoodField.setForeground(Color.black);
        }
    }                                           

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        //TODO
    }                                             

    private void lastnameFieldFocusGained(java.awt.event.FocusEvent evt) {                                          
        if (lastnameField.getText().equals("Silva")){
            lastnameField.setText("");
            lastnameField.setForeground(Color.black);
        }
    }                                         

    private void lastnameFieldFocusLost(java.awt.event.FocusEvent evt) {                                        
        if (lastnameField.getText().equals("")) {
            lastnameField.setText("Silva");
            lastnameField.setForeground(Color.gray);
        }
        else{
            lastnameField.setForeground(Color.black);
        }
    }                                       

    private void nameFieldFocusGained(java.awt.event.FocusEvent evt) {                                      
        if (nameField.getText().equals("João")) {
            nameField.setText("");
            nameField.setForeground(Color.black);
        }
    }                                     

    private void nameFieldFocusLost(java.awt.event.FocusEvent evt) {                                    
        if (nameField.getText().equals("")) {
            nameField.setText("João");
            nameField.setForeground(Color.gray);
        }
        else{
            nameField.setForeground(Color.black);
        }
    }                                   

    private void birthFieldFocusGained(java.awt.event.FocusEvent evt) {                                       
        if (birthField.getText().equals("01/01/2000")){
            birthField.setText("");
            birthField.setForeground(Color.black);
        }
    }                                      

    private void birthFieldFocusLost(java.awt.event.FocusEvent evt) {                                     
        if (birthField.getText().equals("  /  /    ")) {
            birthField.setText("01/01/2000");
            birthField.setForeground(Color.gray);
        }
        else{
            birthField.setForeground(Color.black);
        }
    }                                    

    private void phoneFieldFocusGained(java.awt.event.FocusEvent evt) {                                       
        if (phoneField.getText().equals("(00) 1234-5678")){
            phoneField.setText("");
            phoneField.setForeground(Color.black);
        }
    }                                      

    private void phoneFieldFocusLost(java.awt.event.FocusEvent evt) {                                     
        if (phoneField.getText().equals("(  )     -    ")) {
            phoneField.setText("(00) 1234-5678");
            phoneField.setForeground(Color.gray);
        }
        else{
            phoneField.setForeground(Color.black);
        }
    }                                    

    private void cpfFieldFocusGained(java.awt.event.FocusEvent evt) {                                     
        if (cpfField.getText().equals("111.222.333-00")){
            cpfField.setText("");
            cpfField.setForeground(Color.black);
        }
    }                                    

    private void cpfFieldFocusLost(java.awt.event.FocusEvent evt) {                                   
        if (cpfField.getText().equals("   .   .   -  ")) {
            cpfField.setText("111.222.333-00");
            cpfField.setForeground(Color.gray);
        }
        else{
            cpfField.setForeground(Color.black);
        }
    }                                  

    private void addressFieldFocusGained(java.awt.event.FocusEvent evt) {                                         
        if (addressField.getText().equals("Av. Paulista, 000")){
            addressField.setText("");
            addressField.setForeground(Color.black);
        }
    }                                        

    private void addressFieldFocusLost(java.awt.event.FocusEvent evt) {                                       
        if (addressField.getText().equals("")) {
            addressField.setText("Av. Paulista, 000");
            addressField.setForeground(Color.gray);
        }
        else{
            addressField.setForeground(Color.black);
        }
    }                                      

    private void rgFieldFocusGained(java.awt.event.FocusEvent evt) {                                    
        if (rgField.getText().equals("00.111.999")){
            rgField.setText("");
            rgField.setForeground(Color.black);
        }
    }                                   

    private void rgFieldFocusLost(java.awt.event.FocusEvent evt) {                                  
        if (rgField.getText().equals("  .   .   ")) {
            rgField.setText("00.111.999");
            rgField.setForeground(Color.gray);
        }
        else{
            rgField.setForeground(Color.black);
        }
    }                                 

    private void cellphoneFieldFocusGained(java.awt.event.FocusEvent evt) {                                           
        if (cellphoneField.getText().equals("(00) 1234-5678")){
            cellphoneField.setText("");
            cellphoneField.setForeground(Color.black);
        }
    }                                          

    private void cellphoneFieldFocusLost(java.awt.event.FocusEvent evt) {                                         
        if (cellphoneField.getText().equals("(  )     -    ")) {
            cellphoneField.setText("0012345678");
            cellphoneField.setForeground(Color.gray);
        }
        else{
            cellphoneField.setForeground(Color.black);
        }
    }                                        

    private void loginFieldFocusGained(java.awt.event.FocusEvent evt) {                                       
        if (loginField.getText().equals("SilvaJoao")){
            loginField.setText("");
            loginField.setForeground(Color.black);
        }
    }                                      

    private void loginFieldFocusLost(java.awt.event.FocusEvent evt) {                                     
        if (loginField.getText().equals("")) {
            loginField.setText("SilvaJoao");
            loginField.setForeground(Color.gray);
        }
        else{
            loginField.setForeground(Color.black);
        }
    }                                    

    private void cepFieldFocusGained(java.awt.event.FocusEvent evt) {                                     
        if (cepField.getText().equals("11111-000")){
            cepField.setText("");
            cepField.setForeground(Color.black);
        }
    }                                    

    private void cepFieldFocusLost(java.awt.event.FocusEvent evt) {                                   
        if (cepField.getText().equals("     -   ")) {
            cepField.setText("11111-000");
            cepField.setForeground(Color.gray);
        }
        else{
            cepField.setForeground(Color.black);
        }
    }                                  

    private void passwordFieldFocusGained(java.awt.event.FocusEvent evt) {                                          
        if (Arrays.equals (passwordField.getPassword(), correctPassword)){
            passwordField.setText("");
            passwordField.setForeground(Color.black);
        }
    }                                         

    private void passwordFieldFocusLost(java.awt.event.FocusEvent evt) {                                        
        if (passwordField.getPassword()==null) {
            passwordField.setText("senhadificil");
            passwordField.setForeground(Color.gray);
        }
        else{
            passwordField.setForeground(Color.black);
        }
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new cadastroFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JFormattedTextField birthField;
    private javax.swing.JLabel birthLabel;
    private javax.swing.JFormattedTextField cellphoneField;
    private javax.swing.JLabel cellphoneLabel;
    private javax.swing.JFormattedTextField cepField;
    private javax.swing.JLabel cepLabel;
    private javax.swing.JTextField cityField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JButton confirmButton;
    private javax.swing.JFormattedTextField cpfField;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField lastnameField;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextField loginField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField mailField;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField neighborhoodField;
    private javax.swing.JLabel neighborhoodLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JFormattedTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JFormattedTextField rgField;
    private javax.swing.JLabel rgLabel;
    private javax.swing.JComboBox<String> stateComboBox;
    private javax.swing.JLabel stateLabel;
    // End of variables declaration                   
}
